# Generated by Django 5.1.6 on 2025-02-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_post_content_remove_post_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comment",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
